/**:
  ros__parameters:
    common:
      img_topic: "/left_camera/image"
      lid_topic: "/livox/lidar"
      imu_topic: "/livox/imu"
      img_en: 1
      lidar_en: 1
      ros_driver_bug_fix: false

    extrin_calib:
      extrinsic_T: [0.04165, 0.02326, -0.0284]
      extrinsic_R: [1.0, 0.0, 0.0,
                    0.0, 1.0, 0.0,
                    0.0, 0.0, 1.0]
      Rcl: [0.00610193,-0.999863,-0.0154172,
            -0.00615449,0.0153796,-0.999863,
            0.999962,0.00619598,-0.0060598] 
      Pcl: [0.0194384, 0.104689,-0.0251952]

    time_offset: 
      imu_time_offset: 0.0
      img_time_offset: 0.1
      exposure_time_init: 0.0

    preprocess:
      point_filter_num: 1 #点云滤波次数
      filter_size_surf: 0.1 #表面滤波器尺寸
      lidar_type: 1 # Livox Avia LiDAR
      scan_line: 6
      blind: 0.8 #lidar盲区范围

    vio:
      max_iterations: 5
      outlier_threshold: 1000 # 78 100 156 #100 200 500 700 infinite  离群点阈值
      img_point_cov: 100 # 100 1000  图像特征点协方差
      patch_size: 8 #视觉特征点大小
      patch_pyrimid_level: 4 #视觉特征点金字塔层数
      normal_en: true
      raycast_en: false
      inverse_composition_en: false #是否启用逆组合方法
      exposure_estimate_en: true
      inv_expo_cov: 0.1

    imu:
      imu_en: false
      imu_int_frame: 30
      acc_cov: 0.5 # 0.2
      gyr_cov: 0.3 # 0.5
      b_acc_cov: 0.0001 # 0.1
      b_gyr_cov: 0.0001 # 0.1

    lio:
      max_iterations: 5
      dept_err: 0.02 #深度误差
      beam_err: 0.05 #光束误差
      min_eigen_value: 0.0025 # 0.005 最小特征值  小于该值则视为plane
      voxel_size: 0.5 #体素滤波尺寸
      max_layer: 2
      max_points_num: 50
      layer_init_num: [5, 5, 5, 5, 5]

    local_map:  
      map_sliding_en: false
      half_map_size: 100 #地图窗口半径
      sliding_thresh: 8.0 #地图滑动阈值

    uav:
      imu_rate_odom: false  #是否根据imu频率发布里程计数据
      gravity_align_en: false #是否启用重力对齐

    publish:
      dense_map_en: true  #是否发布稠密地图
      pub_effect_point_en: false 
      pub_plane_en: false
      pub_scan_num: 1
      blind_rgb_points: 0.0 #rgb盲区点云

    evo:
      seq_name: "CBD_Building_01"  #轨迹数据集名称
      pose_output_en: false

    pcd_save:
      pcd_save_en: false #是否保存点云
      colmap_output_en: false # need to set interval = -1
      filter_size_pcd: 0.15 #点云滤波尺寸
      interval: -1
      # how many LiDAR frames saved in each pcd file;
      # -1 : all frames will be saved in ONE pcd file, may lead to memory crash when having too much frames.
